config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, except: :edit
  devise_for :users, except: :show, path_names: { sign_in: "login", sign_out: "logout"}
  get '*path', to: 'application#render_404'

end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user
  validates :user_id,
    presence: true,
    numericality: {only_integer: true, allow_blank: true}
  validates :content,
    length: {maximum: 255, allow_blank: true}
  validates :content_or_image, presence: true

  private
    def content_or_image
      content.presence or image.presence
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  validates :name,
    presence: true,
    uniqueness: true,
    format: { with: /\A[a-z0-9]+\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    "/users/login"
  end

  def render_404(exception = nil)
    if exception
      logger.info "Rendering 404 with exception: #{exception.message}"
    end
    render template: "errors/error_404", status: 404, layout: 'application'
  end

  def render_500(exception = nil)
    if exception
      logger.info "Rendering 500 with exception: #{exception.message}"
    end
    render template: "errors/error_500", status: 500, layout: 'application'
  end


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.page(params[:page]).per(5).order("id DESC")
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :id, :content, :image, :user_id, :deleted_at
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <header id="header" class="clearfix"> <%= render "shared/header" %> </header>

    <%= yield %>

  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post, layout: :horizontal) do |f| %>
  <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |message| %>
        <p class="color-red"><%= message %></p>
      <% end %>
  <% end %>

  <div class="actions">
    <%= f.text_field :content %>
    <%= f.file_field :image %>
    <%= f.hidden_field :user_id, value: current_user.id %>


    <%= f.submit "投稿する", class: "btn btn-primary top-buffer"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="main-wrapper">
  <% if @posts.present? %>
    <% @posts.each do |post| %>
      <div class="main-container border-bottom">
        <div class="post-header clearfix">
          <p class="h4 pull-left right-buffer">by <%= post.user.name %></p>
          <% if post.user_id == current_user.id %>
            <span class="pull-right"><%= link_to '削除', post, method: :delete, data: { confirm: '削除してもよろしいですか？' }, class: "btn btn-default" %></span>
          <% end %>
        </div>
        <p class="h4"><%= post.content if post.content.present? %></p>
        <%= image_tag post.image.thumb.url if post.image.present? %>
      </div>
    <% end %>
  <% else %>
    <h2>投稿はありません</h2>
  <% end %>
  <div class="text-center"><%= paginate(@posts) %></div>
</div>

app/views/posts/new.html.erb
<div class="main-wrapper">
  <div class="main-container">
    <h1 class="bottom-buffer">New Post</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_header.html.erb
<h1 class="pull-left"><%= link_to "OneBoard", root_path %></h1>
<% if user_signed_in? %>
  <span id="logined_option" class="pull-right top-buffer">
    <%= link_to "投稿する", new_post_path, class: 'btn btn-default' %></small>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-default', data: {confirm: "ログアウトしてもよろしいですか？"} %></small>
  </span>
<% else %>
  <span id="logouted_option" class="pull-right top-buffer">
    <%= link_to "ログイン", new_user_session_path, class: 'btn btn-default' %></small>
    <%= link_to "登録", new_user_registration_path, class: 'btn btn-default' %></small>
  </span>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>